### ISSUE TITLE
webpush:generate:keys command does not exist

### ISSUE THREAD

**Issue by tv78-coder** [bpolaszek/webpush-bundle#15] opened 2019-09-29 10:17 UTC
Hello, i am using SF 4.3. After i install this bundle, the `php bin/console webpush:generate:keys` is undefined and i don't see the configuration file either. How should i do?

**Comment by bpolaszek** [comment] 2019-09-30 08:00
Hey there,

It looks like the bundle is no longer automatically registered in `config/bundles.php`, I was able to reproduce this. Can you please add it manually?

I'll try to have a look at this  later.

**Comment by bpolaszek** [comment] 2019-09-30 12:18
Fixed in 0.5.1.

**Closed** 2019-09-30 12:17 UTC
